server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9004}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9005}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

tokenExpirationTime: 3600000
authenticationUrl: "/authenticate"

security:
  jwtSecret: ${JWT_SECRET}
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"

#important section if you use logstash
logging:
  level: INFO
  appenders:
    - type: tcp
      host: ${LOGSTASH_IP:-192.168.99.100}
      port: ${LOGSTASH_PORT:-5600}
      #log pattern that includes all necessary information
      logFormat: "%-5level [%X{correlationId}] [${SERVICE_NAME:-Authoriser}] [%date{ISO8601}] %c %message%n"
    - type: console
      logFormat: "%-5level [%X{correlationId}] [${SERVICE_NAME:-Authoriser}] [%date{ISO8601}] %c %message%n"
