server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9004}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9005}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

tokenExpirationTime: 3600000
authenticationUrl: "/authenticate"

security:
  jwtSecret: ${JWT_SECRET}
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"

googleOauth:
  clientId: ${GOOGLE_OAUTH_CLIENT_ID:-216227526446-v8cvofejk8thpjon3ro855ef29r5jkpq.apps.googleusercontent.com}
  clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET:-aSUEBFrgLGj9BmY6RvN-ZUj6}
