server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9004}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9005}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

tokenExpirationTime: 3600000
authenticationUrl: "/authenticate"

security:
  jwtSecret: ${JWT_SECRET}
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"

googleOauth:
  clientId: 216227526446-v8cvofejk8thpjon3ro855ef29r5jkpq.apps.googleusercontent.com
  clientSecret: aSUEBFrgLGj9BmY6RvN-ZUj6
  authorisationUri: https://accounts.google.com/o/oauth2/v2/auth
  tokenUri: https://www.googleapis.com/oauth2/v4/token
  userInfoUri: https://www.googleapis.com/oauth2/v1/userinfo
  scope: https://www.googleapis.com/auth/userinfo.profile
  #change localhost:9004 to another address
  redirectUri: http://localhost:9004/oauth2/code/google
