server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

database:
  url: jdbc:mysql://localhost:3306/bookstore
  username: root
  password: 1234
  driver: com.mysql.cj.jdbc.Driver