server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9006}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9007}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

libraryService:
  url: http://${LIBRARY_SERVICE_IP:-localhost}:${LIBRARY_SERVICE_PORT:-9000}

mailSenderService:
  url: http://${MAIL_SENDER_SERVICE_IP:-localhost}:${MAIL_SENDER_SERVICE_PORT:-9008}

loggerService:
  url: http://${LOGGER_SERVICE_IP:-localhost}:${LOGGER_SERVICE_PORT:-9002}

feeChargeConfig:
  rentPeriod: 1
  checkExpirationInterval: 1

oktaOAuth:
  baseUrl: "https://dev-702765.okta.com"
  issuer: "https://dev-702765.okta.com/oauth2/default"
  tokenPath: "https://dev-702765.okta.com/oauth2/default/v1/token"
  clientId: "0oa1iyrvx8grc62vY357"
  clientSecret: ${OKTA_FEECHARGER_SECRET}
  scopes:
    - write
logging:
  level: INFO

kafkaConfig:
  brokerUrl: http://192.168.99.100:9092
  schemaRegistryUrl: http://192.168.99.100:8081

kafkaMailTopic: MailTopic

kafkaUserBookPaymentLogTopic: UserBookPaymentLogTopic

awsS3Config:
  accessKey: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  bucketName: bookstorebucket
  allowedFileTypes:
    - pdf
    - txt
  allowedImageTypes:
    - jpg
    - png
  maxFileSize: 314572800    #300MB
  maxImageSize: 26214400   #25MB

invoiceLambdaGeneratorUrl: hts