server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9010}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9011}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

awsS3Config:
  accessKey: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  bucketName: bookstorebucket
  allowedFileTypes:
    - pdf
    - txt
  allowedImageTypes:
    - jpg
    - png
  maxFileSize: 314572800    #300MB
  maxImageSize: 26214400   #25MB

invoiceGeneratorLambdaUrl: https://qerhbbqfd2.execute-api.us-east-2.amazonaws.com/default/InvoicePDFGenerator

kafkaConfig:
  brokerUrl: http://192.168.99.100:9092
  schemaRegistryUrl: http://192.168.99.100:8081

invoicerConfig:
  generateInvoicePeriod: 1

kafkaInvoiceActionTopic: InvoiceActionTopic

#important section if you use logstash
logging:
  level: INFO
  appenders:
    - type: tcp
      host: ${LOGSTASH_IP:-192.168.99.100}
      port: ${LOGSTASH_PORT:-5600}
      #log pattern that includes all necessary information
      logFormat: "%-5level [%X{correlationId}] [${SERVICE_NAME:-Invoicer}] [%date{ISO8601}] %c %message%n"
    - type: console
      logFormat: "%-5level [%X{correlationId}] [${SERVICE_NAME:-Invoicer}] [%date{ISO8601}] %c %message%n"
