server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9000}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9001}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: root
  password: 1234
  driverClass: com.mysql.cj.jdbc.Driver

clientBookLoggerService:
  url: http://${LOGGER_SERVICE_IP:-localhost}:${LOGGER_SERVICE_PORT:-9002}

security:
  authenticationUrl: "/authenticate"
  jwtSecret: "n2r5u8xfdg02aPdSgVkYp3s6321gfdretewrhWmZq4t7w!z%C*F-Jdsfdsfq23234dsfds@NcRf"
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"