server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9000}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9001}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

clientBookLoggerService:
  url: http://${LOGGER_SERVICE_URL:-localhost:9002}

security:
  jwtSecret: "n2r5u8xfdg02aPdSgVkYp3s6321gfdretewrhWmZq4t7w!z%C*F-Jdsfdsfq23234dsfds@NcRf"
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"

oktaOAuth:
  baseUrl: "https://dev-702765.okta.com"
  issuer: "https://dev-702765.okta.com/oauth2/default"
  tokenPath: "https://dev-702765.okta.com/oauth2/default/v1/token"
  clientId: "0oa1ep4cgrcPMejCk357"
  clientSecret: "x2ObRXn2tHLIjwKSe_Hwm8vT5DWHJPAYKG8JhwUQ"
  scopes:
    - write


swagger:
  resourcePackage: com.resources

logging:
  level: INFO