server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: root
  password: 1234
  driverClass: com.mysql.cj.jdbc.Driver

clientBookLoggerService:
  url: http://localhost:9002