server:
  applicationConnectors:
    - type: http
      port: 9002
  adminConnectors:
    - type: http
      port: 9003

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: root
  password: 1234
  driverClass: com.mysql.cj.jdbc.Driver