server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9002}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9003}

database:
  url: jdbc:mysql://${DB_IP:-localhost}:3306/${DB_NAME:-bookstore}
  user: ${DB_USERNAME:-root}
  password: ${DB_PASSWORD:-1234}
  driverClass: com.mysql.cj.jdbc.Driver

security:
  jwtSecret: ${JWT_SECRET}
  tokenHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenType: "JWT"

oktaOAuth:
  baseUrl: "https://dev-702765.okta.com"
  issuer: "https://dev-702765.okta.com/oauth2/default"
  tokenPath: "https://dev-702765.okta.com/oauth2/default/v1/token"
  clientId: "0oa1epfonjxBlFUoa357"
  clientSecret: ${OKTA_LOGGER_SECRET}

swagger:
  resourcePackage: com.resources

kafkaConfig:
  brokerUrl: ${BROKER_URL:-http://192.168.99.100:9092}
  schemaRegistryUrl: ${SCHEMA_REGISTRY_URL:-http://192.168.99.100:8081}

kafkaUserBookPaymentLogTopic: UserBookPaymentLogTopic

kafkaUserBookActionTopic: UserBookActionTopic

kafkaUserBookPaymentActionTopic: UserBookPaymentActionTopic