server:
  applicationConnectors:
    - type: http
      port: ${SERVICE_CLIENTPORT:-9008}
  adminConnectors:
    - type: http
      port: ${SERVICE_ADMINPORT:-9009}

mailConfig:
  username: bookstore.noreply.service@gmail.com
  password: kmaowuxuwzlxmzsy
  fromName: Bookstore
  fromAddress: bookstore.noreply.service@gmail.com

oktaOAuth:
  baseUrl: "https://dev-702765.okta.com"
  issuer: "https://dev-702765.okta.com/oauth2/default"
  tokenPath: "https://dev-702765.okta.com/oauth2/default/v1/token"
  clientId: "0oa1j89ftf8jgPY1Q357"
  clientSecret: ${OKTA_MAILSENDER_SECRET}