server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001

database:
  url: jdbc:mysql://localhost:3306/bookstore
  user: root
  password: 1234
  driverClass: com.mysql.cj.jdbc.Driver