version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - elk-network

    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        container_name: kibana
        ports:
            - '5601:5601'
        depends_on:
            -  elasticsearch
        networks:
            - elk-network

    logstash:
        image: docker.elastic.co/logstash/logstash:6.3.2
        container_name: logstash
        ports:
            - '25826:25826'
            - '5600:5600'
        volumes:
            - ./elk-config:/elk-config
        command: logstash -f /elk-config/logstash.config
        depends_on:
            -  elasticsearch
        networks:
            - elk-network
networks:
    elk-network: