/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroUserChangedEmailAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3915551034703581304L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroUserChangedEmailAction\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"newEmail\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroUserChangedEmailAction> ENCODER =
      new BinaryMessageEncoder<AvroUserChangedEmailAction>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroUserChangedEmailAction> DECODER =
      new BinaryMessageDecoder<AvroUserChangedEmailAction>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroUserChangedEmailAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroUserChangedEmailAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroUserChangedEmailAction>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroUserChangedEmailAction to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroUserChangedEmailAction from a ByteBuffer. */
  public static AvroUserChangedEmailAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long userId;
  @Deprecated public java.lang.CharSequence newEmail;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroUserChangedEmailAction() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param newEmail The new value for newEmail
   */
  public AvroUserChangedEmailAction(java.lang.Long userId, java.lang.CharSequence newEmail) {
    this.userId = userId;
    this.newEmail = newEmail;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return newEmail;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: newEmail = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'newEmail' field.
   * @return The value of the 'newEmail' field.
   */
  public java.lang.CharSequence getNewEmail() {
    return newEmail;
  }

  /**
   * Sets the value of the 'newEmail' field.
   * @param value the value to set.
   */
  public void setNewEmail(java.lang.CharSequence value) {
    this.newEmail = value;
  }

  /**
   * Creates a new AvroUserChangedEmailAction RecordBuilder.
   * @return A new AvroUserChangedEmailAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder newBuilder() {
    return new com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder();
  }

  /**
   * Creates a new AvroUserChangedEmailAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroUserChangedEmailAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder other) {
    return new com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder(other);
  }

  /**
   * Creates a new AvroUserChangedEmailAction RecordBuilder by copying an existing AvroUserChangedEmailAction instance.
   * @param other The existing instance to copy.
   * @return A new AvroUserChangedEmailAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction other) {
    return new com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder(other);
  }

  /**
   * RecordBuilder for AvroUserChangedEmailAction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroUserChangedEmailAction>
    implements org.apache.avro.data.RecordBuilder<AvroUserChangedEmailAction> {

    private long userId;
    private java.lang.CharSequence newEmail;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.newEmail)) {
        this.newEmail = data().deepCopy(fields()[1].schema(), other.newEmail);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroUserChangedEmailAction instance
     * @param other The existing instance to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.newEmail)) {
        this.newEmail = data().deepCopy(fields()[1].schema(), other.newEmail);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'newEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewEmail() {
      return newEmail;
    }

    /**
      * Sets the value of the 'newEmail' field.
      * @param value The value of 'newEmail'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder setNewEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.newEmail = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'newEmail' field has been set.
      * @return True if the 'newEmail' field has been set, false otherwise.
      */
    public boolean hasNewEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'newEmail' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserChangedEmailAction.Builder clearNewEmail() {
      newEmail = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroUserChangedEmailAction build() {
      try {
        AvroUserChangedEmailAction record = new AvroUserChangedEmailAction();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.newEmail = fieldSetFlags()[1] ? this.newEmail : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroUserChangedEmailAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroUserChangedEmailAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroUserChangedEmailAction>
    READER$ = (org.apache.avro.io.DatumReader<AvroUserChangedEmailAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
