/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroBookAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8276206670097374333L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroBookAction\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"fields\":[{\"name\":\"bookId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"AvroBookActionStatus\",\"symbols\":[\"CREATED\",\"DELETED\",\"UPDATED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroBookAction> ENCODER =
      new BinaryMessageEncoder<AvroBookAction>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroBookAction> DECODER =
      new BinaryMessageDecoder<AvroBookAction>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroBookAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroBookAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroBookAction>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroBookAction to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroBookAction from a ByteBuffer. */
  public static AvroBookAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long bookId;
  @Deprecated public com.softserveinc.cross_api_objects.avro.AvroBookActionStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroBookAction() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param status The new value for status
   */
  public AvroBookAction(java.lang.Long bookId, com.softserveinc.cross_api_objects.avro.AvroBookActionStatus status) {
    this.bookId = bookId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.Long)value$; break;
    case 1: status = (com.softserveinc.cross_api_objects.avro.AvroBookActionStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.Long getBookId() {
    return bookId;
  }

  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.Long value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.softserveinc.cross_api_objects.avro.AvroBookActionStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.softserveinc.cross_api_objects.avro.AvroBookActionStatus value) {
    this.status = value;
  }

  /**
   * Creates a new AvroBookAction RecordBuilder.
   * @return A new AvroBookAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder newBuilder() {
    return new com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder();
  }

  /**
   * Creates a new AvroBookAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroBookAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder other) {
    return new com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder(other);
  }

  /**
   * Creates a new AvroBookAction RecordBuilder by copying an existing AvroBookAction instance.
   * @param other The existing instance to copy.
   * @return A new AvroBookAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroBookAction other) {
    return new com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder(other);
  }

  /**
   * RecordBuilder for AvroBookAction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroBookAction>
    implements org.apache.avro.data.RecordBuilder<AvroBookAction> {

    private long bookId;
    private com.softserveinc.cross_api_objects.avro.AvroBookActionStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroBookAction instance
     * @param other The existing instance to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroBookAction other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.Long getBookId() {
      return bookId;
    }

    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder setBookId(long value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder clearBookId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.softserveinc.cross_api_objects.avro.AvroBookActionStatus getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder setStatus(com.softserveinc.cross_api_objects.avro.AvroBookActionStatus value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroBookAction.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroBookAction build() {
      try {
        AvroBookAction record = new AvroBookAction();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.Long) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (com.softserveinc.cross_api_objects.avro.AvroBookActionStatus) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroBookAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroBookAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroBookAction>
    READER$ = (org.apache.avro.io.DatumReader<AvroBookAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
