/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AvroAction {
  TAKE, RETURN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroAction\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"symbols\":[\"TAKE\",\"RETURN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
