/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AvroBookActionStatus {
  CREATED, DELETED, UPDATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroBookActionStatus\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"symbols\":[\"CREATED\",\"DELETED\",\"UPDATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
