/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroMail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7777313727378974548L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroMail\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"fields\":[{\"name\":\"receiverEmaill\",\"type\":\"string\"},{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"},{\"name\":\"attachment\",\"type\":[{\"type\":\"record\",\"name\":\"AvroAttachment\",\"fields\":[{\"name\":\"attachmentUrl\",\"type\":\"string\"},{\"name\":\"attachmentName\",\"type\":\"string\"}]},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroMail> ENCODER =
      new BinaryMessageEncoder<AvroMail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroMail> DECODER =
      new BinaryMessageDecoder<AvroMail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroMail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroMail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroMail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroMail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroMail from a ByteBuffer. */
  public static AvroMail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence receiverEmaill;
  @Deprecated public java.lang.CharSequence subject;
  @Deprecated public java.lang.CharSequence body;
  @Deprecated public com.softserveinc.cross_api_objects.avro.AvroAttachment attachment;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroMail() {}

  /**
   * All-args constructor.
   * @param receiverEmaill The new value for receiverEmaill
   * @param subject The new value for subject
   * @param body The new value for body
   * @param attachment The new value for attachment
   */
  public AvroMail(java.lang.CharSequence receiverEmaill, java.lang.CharSequence subject, java.lang.CharSequence body, com.softserveinc.cross_api_objects.avro.AvroAttachment attachment) {
    this.receiverEmaill = receiverEmaill;
    this.subject = subject;
    this.body = body;
    this.attachment = attachment;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return receiverEmaill;
    case 1: return subject;
    case 2: return body;
    case 3: return attachment;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: receiverEmaill = (java.lang.CharSequence)value$; break;
    case 1: subject = (java.lang.CharSequence)value$; break;
    case 2: body = (java.lang.CharSequence)value$; break;
    case 3: attachment = (com.softserveinc.cross_api_objects.avro.AvroAttachment)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'receiverEmaill' field.
   * @return The value of the 'receiverEmaill' field.
   */
  public java.lang.CharSequence getReceiverEmaill() {
    return receiverEmaill;
  }

  /**
   * Sets the value of the 'receiverEmaill' field.
   * @param value the value to set.
   */
  public void setReceiverEmaill(java.lang.CharSequence value) {
    this.receiverEmaill = value;
  }

  /**
   * Gets the value of the 'subject' field.
   * @return The value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }

  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'body' field.
   * @return The value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /**
   * Gets the value of the 'attachment' field.
   * @return The value of the 'attachment' field.
   */
  public com.softserveinc.cross_api_objects.avro.AvroAttachment getAttachment() {
    return attachment;
  }

  /**
   * Sets the value of the 'attachment' field.
   * @param value the value to set.
   */
  public void setAttachment(com.softserveinc.cross_api_objects.avro.AvroAttachment value) {
    this.attachment = value;
  }

  /**
   * Creates a new AvroMail RecordBuilder.
   * @return A new AvroMail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroMail.Builder newBuilder() {
    return new com.softserveinc.cross_api_objects.avro.AvroMail.Builder();
  }

  /**
   * Creates a new AvroMail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroMail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroMail.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroMail.Builder other) {
    return new com.softserveinc.cross_api_objects.avro.AvroMail.Builder(other);
  }

  /**
   * Creates a new AvroMail RecordBuilder by copying an existing AvroMail instance.
   * @param other The existing instance to copy.
   * @return A new AvroMail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroMail.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroMail other) {
    return new com.softserveinc.cross_api_objects.avro.AvroMail.Builder(other);
  }

  /**
   * RecordBuilder for AvroMail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroMail>
    implements org.apache.avro.data.RecordBuilder<AvroMail> {

    private java.lang.CharSequence receiverEmaill;
    private java.lang.CharSequence subject;
    private java.lang.CharSequence body;
    private com.softserveinc.cross_api_objects.avro.AvroAttachment attachment;
    private com.softserveinc.cross_api_objects.avro.AvroAttachment.Builder attachmentBuilder;

    /** Creates a new Builder */
    Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroMail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.receiverEmaill)) {
        this.receiverEmaill = data().deepCopy(fields()[0].schema(), other.receiverEmaill);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.attachment)) {
        this.attachment = data().deepCopy(fields()[3].schema(), other.attachment);
        fieldSetFlags()[3] = true;
      }
      if (other.hasAttachmentBuilder()) {
        this.attachmentBuilder = com.softserveinc.cross_api_objects.avro.AvroAttachment.newBuilder(other.getAttachmentBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AvroMail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroMail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.receiverEmaill)) {
        this.receiverEmaill = data().deepCopy(fields()[0].schema(), other.receiverEmaill);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.attachment)) {
        this.attachment = data().deepCopy(fields()[3].schema(), other.attachment);
        fieldSetFlags()[3] = true;
      }
      this.attachmentBuilder = null;
    }

    /**
      * Gets the value of the 'receiverEmaill' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceiverEmaill() {
      return receiverEmaill;
    }

    /**
      * Sets the value of the 'receiverEmaill' field.
      * @param value The value of 'receiverEmaill'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder setReceiverEmaill(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.receiverEmaill = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverEmaill' field has been set.
      * @return True if the 'receiverEmaill' field has been set, false otherwise.
      */
    public boolean hasReceiverEmaill() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'receiverEmaill' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder clearReceiverEmaill() {
      receiverEmaill = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return subject;
    }

    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.subject = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'body' field.
      * @return The value.
      */
    public java.lang.CharSequence getBody() {
      return body;
    }

    /**
      * Sets the value of the 'body' field.
      * @param value The value of 'body'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.body = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'body' field has been set.
      * @return True if the 'body' field has been set, false otherwise.
      */
    public boolean hasBody() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'body' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder clearBody() {
      body = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'attachment' field.
      * @return The value.
      */
    public com.softserveinc.cross_api_objects.avro.AvroAttachment getAttachment() {
      return attachment;
    }

    /**
      * Sets the value of the 'attachment' field.
      * @param value The value of 'attachment'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder setAttachment(com.softserveinc.cross_api_objects.avro.AvroAttachment value) {
      validate(fields()[3], value);
      this.attachmentBuilder = null;
      this.attachment = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'attachment' field has been set.
      * @return True if the 'attachment' field has been set, false otherwise.
      */
    public boolean hasAttachment() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'attachment' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.softserveinc.cross_api_objects.avro.AvroAttachment.Builder getAttachmentBuilder() {
      if (attachmentBuilder == null) {
        if (hasAttachment()) {
          setAttachmentBuilder(com.softserveinc.cross_api_objects.avro.AvroAttachment.newBuilder(attachment));
        } else {
          setAttachmentBuilder(com.softserveinc.cross_api_objects.avro.AvroAttachment.newBuilder());
        }
      }
      return attachmentBuilder;
    }

    /**
     * Sets the Builder instance for the 'attachment' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder setAttachmentBuilder(com.softserveinc.cross_api_objects.avro.AvroAttachment.Builder value) {
      clearAttachment();
      attachmentBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'attachment' field has an active Builder instance
     * @return True if the 'attachment' field has an active Builder instance
     */
    public boolean hasAttachmentBuilder() {
      return attachmentBuilder != null;
    }

    /**
      * Clears the value of the 'attachment' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroMail.Builder clearAttachment() {
      attachment = null;
      attachmentBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroMail build() {
      try {
        AvroMail record = new AvroMail();
        record.receiverEmaill = fieldSetFlags()[0] ? this.receiverEmaill : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.subject = fieldSetFlags()[1] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.body = fieldSetFlags()[2] ? this.body : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (attachmentBuilder != null) {
          record.attachment = this.attachmentBuilder.build();
        } else {
          record.attachment = fieldSetFlags()[3] ? this.attachment : (com.softserveinc.cross_api_objects.avro.AvroAttachment) defaultValue(fields()[3]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroMail>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroMail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroMail>
    READER$ = (org.apache.avro.io.DatumReader<AvroMail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
