/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroUserBookExtendAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1398337421394280090L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroUserBookExtendAction\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"bookId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"AvroUserBookExtendActionStatus\",\"symbols\":[\"SUCCEED\",\"NOT_ENOUGH_MONEY\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroUserBookExtendAction> ENCODER =
      new BinaryMessageEncoder<AvroUserBookExtendAction>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroUserBookExtendAction> DECODER =
      new BinaryMessageDecoder<AvroUserBookExtendAction>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroUserBookExtendAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroUserBookExtendAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroUserBookExtendAction>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroUserBookExtendAction to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroUserBookExtendAction from a ByteBuffer. */
  public static AvroUserBookExtendAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long userId;
  @Deprecated public long bookId;
  @Deprecated public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroUserBookExtendAction() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param bookId The new value for bookId
   * @param status The new value for status
   */
  public AvroUserBookExtendAction(java.lang.Long userId, java.lang.Long bookId, com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus status) {
    this.userId = userId;
    this.bookId = bookId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return bookId;
    case 2: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: bookId = (java.lang.Long)value$; break;
    case 2: status = (com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.Long getBookId() {
    return bookId;
  }

  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.Long value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus value) {
    this.status = value;
  }

  /**
   * Creates a new AvroUserBookExtendAction RecordBuilder.
   * @return A new AvroUserBookExtendAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder newBuilder() {
    return new com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder();
  }

  /**
   * Creates a new AvroUserBookExtendAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroUserBookExtendAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder other) {
    return new com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder(other);
  }

  /**
   * Creates a new AvroUserBookExtendAction RecordBuilder by copying an existing AvroUserBookExtendAction instance.
   * @param other The existing instance to copy.
   * @return A new AvroUserBookExtendAction RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder newBuilder(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction other) {
    return new com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder(other);
  }

  /**
   * RecordBuilder for AvroUserBookExtendAction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroUserBookExtendAction>
    implements org.apache.avro.data.RecordBuilder<AvroUserBookExtendAction> {

    private long userId;
    private long bookId;
    private com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookId)) {
        this.bookId = data().deepCopy(fields()[1].schema(), other.bookId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroUserBookExtendAction instance
     * @param other The existing instance to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookId)) {
        this.bookId = data().deepCopy(fields()[1].schema(), other.bookId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.Long getBookId() {
      return bookId;
    }

    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder setBookId(long value) {
      validate(fields()[1], value);
      this.bookId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder clearBookId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder setStatus(com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.AvroUserBookExtendAction.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroUserBookExtendAction build() {
      try {
        AvroUserBookExtendAction record = new AvroUserBookExtendAction();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.bookId = fieldSetFlags()[1] ? this.bookId : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (com.softserveinc.cross_api_objects.avro.AvroUserBookExtendActionStatus) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroUserBookExtendAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroUserBookExtendAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroUserBookExtendAction>
    READER$ = (org.apache.avro.io.DatumReader<AvroUserBookExtendAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
