/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.softserveinc.cross_api_objects.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Mail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2095831788931459775L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Mail\",\"namespace\":\"com.softserveinc.cross_api_objects.avro\",\"fields\":[{\"name\":\"receiverEmaill\",\"type\":\"string\"},{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Mail> ENCODER =
      new BinaryMessageEncoder<Mail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Mail> DECODER =
      new BinaryMessageDecoder<Mail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Mail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Mail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Mail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Mail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Mail from a ByteBuffer. */
  public static Mail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence receiverEmaill;
  @Deprecated public java.lang.CharSequence subject;
  @Deprecated public java.lang.CharSequence body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Mail() {}

  /**
   * All-args constructor.
   * @param receiverEmaill The new value for receiverEmaill
   * @param subject The new value for subject
   * @param body The new value for body
   */
  public Mail(java.lang.CharSequence receiverEmaill, java.lang.CharSequence subject, java.lang.CharSequence body) {
    this.receiverEmaill = receiverEmaill;
    this.subject = subject;
    this.body = body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return receiverEmaill;
    case 1: return subject;
    case 2: return body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: receiverEmaill = (java.lang.CharSequence)value$; break;
    case 1: subject = (java.lang.CharSequence)value$; break;
    case 2: body = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'receiverEmaill' field.
   * @return The value of the 'receiverEmaill' field.
   */
  public java.lang.CharSequence getReceiverEmaill() {
    return receiverEmaill;
  }

  /**
   * Sets the value of the 'receiverEmaill' field.
   * @param value the value to set.
   */
  public void setReceiverEmaill(java.lang.CharSequence value) {
    this.receiverEmaill = value;
  }

  /**
   * Gets the value of the 'subject' field.
   * @return The value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }

  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'body' field.
   * @return The value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /**
   * Creates a new Mail RecordBuilder.
   * @return A new Mail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.Mail.Builder newBuilder() {
    return new com.softserveinc.cross_api_objects.avro.Mail.Builder();
  }

  /**
   * Creates a new Mail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Mail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.Mail.Builder newBuilder(com.softserveinc.cross_api_objects.avro.Mail.Builder other) {
    return new com.softserveinc.cross_api_objects.avro.Mail.Builder(other);
  }

  /**
   * Creates a new Mail RecordBuilder by copying an existing Mail instance.
   * @param other The existing instance to copy.
   * @return A new Mail RecordBuilder
   */
  public static com.softserveinc.cross_api_objects.avro.Mail.Builder newBuilder(com.softserveinc.cross_api_objects.avro.Mail other) {
    return new com.softserveinc.cross_api_objects.avro.Mail.Builder(other);
  }

  /**
   * RecordBuilder for Mail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Mail>
    implements org.apache.avro.data.RecordBuilder<Mail> {

    private java.lang.CharSequence receiverEmaill;
    private java.lang.CharSequence subject;
    private java.lang.CharSequence body;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.Mail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.receiverEmaill)) {
        this.receiverEmaill = data().deepCopy(fields()[0].schema(), other.receiverEmaill);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Mail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.softserveinc.cross_api_objects.avro.Mail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.receiverEmaill)) {
        this.receiverEmaill = data().deepCopy(fields()[0].schema(), other.receiverEmaill);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subject)) {
        this.subject = data().deepCopy(fields()[1].schema(), other.subject);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body)) {
        this.body = data().deepCopy(fields()[2].schema(), other.body);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'receiverEmaill' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceiverEmaill() {
      return receiverEmaill;
    }

    /**
      * Sets the value of the 'receiverEmaill' field.
      * @param value The value of 'receiverEmaill'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder setReceiverEmaill(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.receiverEmaill = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverEmaill' field has been set.
      * @return True if the 'receiverEmaill' field has been set, false otherwise.
      */
    public boolean hasReceiverEmaill() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'receiverEmaill' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder clearReceiverEmaill() {
      receiverEmaill = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return subject;
    }

    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.subject = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'body' field.
      * @return The value.
      */
    public java.lang.CharSequence getBody() {
      return body;
    }

    /**
      * Sets the value of the 'body' field.
      * @param value The value of 'body'.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.body = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'body' field has been set.
      * @return True if the 'body' field has been set, false otherwise.
      */
    public boolean hasBody() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'body' field.
      * @return This builder.
      */
    public com.softserveinc.cross_api_objects.avro.Mail.Builder clearBody() {
      body = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Mail build() {
      try {
        Mail record = new Mail();
        record.receiverEmaill = fieldSetFlags()[0] ? this.receiverEmaill : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.subject = fieldSetFlags()[1] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.body = fieldSetFlags()[2] ? this.body : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Mail>
    WRITER$ = (org.apache.avro.io.DatumWriter<Mail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Mail>
    READER$ = (org.apache.avro.io.DatumReader<Mail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
